apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  selector:
    app: website
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  selector:
    matchLabels:
      app: website
  replicas: 2
  template:
    metadata:
      labels:
        app: website
    spec:
      serviceAccountName: workload-identity-sa
      containers:
        - name: website
          imagePullPolicy: Always
          image: nginx:latest
          ports:
            - containerPort: 8443
          volumeMounts:
          - mountPath: /etc/nginx/ssl
            name: secrets-store-inline
            readOnly: true
          - mountPath: /etc/nginx/conf.d
            name: configmap-volume-1
          - mountPath: /usr/share/nginx/html/index.html
            name: configmap-volume-2
            subPath: index.html
      volumes:
      - name: configmap-volume-1
        configMap:
          name: website-nginx-cm
      - name: configmap-volume-2
        configMap:
          name: index-nginx-cm
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-tls"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: website-nginx-cm
data:
  default.conf: |-
    server {
        listen 8080 default_server;
        listen 8443 ssl;
        root /usr/share/nginx/html;
        index index.html;
        ssl_certificate /etc/nginx/ssl/${CERT_NAME}.crt;
        ssl_certificate_key /etc/nginx/ssl/${CERT_NAME}.key;
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-nginx-cm
data:
  index.html: <html>Hello World!</html>